version: '3'

services:
  # Webサーバ
  nginx:
    container_name: pripla_nginx
    hostname: pripla_nginx
    image: nginx
    ports:
      - ${APP_EXPOSE_PORT}:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    environment:
      TZ: 'Asia/Tokyo'
    depends_on:
      - php
    networks:
      - pripla
    restart: always

  # Web API
  php:
    container_name: pripla_php
    hostname: pripla_php
    build: ./docker/php
    volumes:
      - .:/var/www:cached
    environment:
      TZ: 'Asia/Tokyo'
    depends_on:
      - mysql
    networks:
      - pripla
    restart: always

  # データベース
  mysql:
    container_name: pripla_mysql
    hostname: pripla_mysql
    image: mysql:5.7
    ports:
      - ${DB_EXPOSE_PORT}:${DB_PORT}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:cached
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo'
    networks:
      - pripla
    restart: always

networks:
  pripla:
    external: true
